# This is the config file for DLtreeseg program. Program use metric system
[IO]
WORKDIR = "/home/vscode/remotehome/DL_drake/output"
TRAIN_RASTER_DIR = "/home/vscode/remotehome/DL_drake/Drake/Ref"
TRAIN_SHP_DIR = "/home/vscode/remotehome/DL_drake/shp"
PREDICT_RASTER_DIR = "/home/vscode/remotehome/DL_drake/Drake/predict"

[PREPROCESS]
TILE_SIZE = 256 # meter
BUFFER_SIZE = 10 # meter
DEBUG = false
MODE = 'BGR'

[PREPROCESS.RESAMPLE]
ENABLE = false
RESOLUTION = 0.1 # meter

[PREPROCESS.COCO_INFO]
NAME = 'testdataset'
VERSION = '1.0'
DESCRIPTION = 'This is a test dataset'
CONTRIBUTOR = 'unknown'
URL = "unknown"
# You can add as much descriptions as you want under this section.
# e.g.
# time = '2019-08-24'
# email = 'myemail@email.com'
[TRAIN]
MODEL = 'maskrcnn_rgb' # other model option in the furture
ACCELERATOR = 'gpu'
DEVICES = 1
MAX_EPOCHS = 100

[TRAIN.DATAMODULE]
BATCH_SIZE = 5
NUM_WORKERS = 2
TRANSOFRM = 'default' # Or customized transform file path

[TRAIN.MASKRCNNRGB]
NUM_CLASSES = 2
LEARNING_RATE = 1e-3
